# Generated by Django 5.0.2 on 2024-03-19 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='mum_credits',
            new_name='num_credits',
        ),
        migrations.RenameField(
            model_name='major',
            old_name='mum_credits',
            new_name='num_credits',
        ),
        migrations.RenameField(
            model_name='minor',
            old_name='mum_credits',
            new_name='num_credits',
        ),
    ]
