# Generated by Django 5.0.2 on 2024-04-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planner',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planner',
            name='name',
            field=models.CharField(default='Best', max_length=100),
            preserve_default=False,
        ),
    ]
