# Generated by Django 5.0.2 on 2024-04-01 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubjectArea',
            new_name='Subject',
        ),
    ]
