# Generated by Django 5.0.2 on 2024-03-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='class_year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='admin',
            name='eagle_id',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='eagle_id',
            field=models.CharField(max_length=8),
        ),
    ]
