# Generated by Django 5.0.2 on 2024-03-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('ADVISOR', 'Advisor')], default='STUDENT', max_length=7),
        ),
    ]
