# Generated by Django 5.0.2 on 2024-04-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planner',
            old_name='sem_seven',
            new_name='fall_four',
        ),
        migrations.RenameField(
            model_name='planner',
            old_name='sem_one',
            new_name='fall_one',
        ),
        migrations.RenameField(
            model_name='planner',
            old_name='sem_five',
            new_name='fall_three',
        ),
        migrations.RenameField(
            model_name='planner',
            old_name='sem_three',
            new_name='fall_two',
        ),
        migrations.RenameField(
            model_name='planner',
            old_name='sem_eight',
            new_name='spring_four',
        ),
        migrations.RenameField(
            model_name='planner',
            old_name='sem_two',
            new_name='spring_one',
        ),
        migrations.RenameField(
            model_name='planner',
            old_name='sem_six',
            new_name='spring_three',
        ),
        migrations.RenameField(
            model_name='planner',
            old_name='sem_four',
            new_name='spring_two',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='class_five',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='class_four',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='class_one',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='class_six',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='class_three',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='class_two',
        ),
        migrations.AddField(
            model_name='semester',
            name='courses',
            field=models.ManyToManyField(to='planner.course'),
        ),
        migrations.AddField(
            model_name='semester',
            name='credit_hours',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.CheckConstraint(check=models.Q(('credit_hours__lte', 21)), name='credit_hours_limit'),
        ),
    ]
