# Generated by Django 5.0.2 on 2024-04-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_planner_description_planner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='courses',
            field=models.ManyToManyField(blank=True, default=None, to='planner.course'),
        ),
    ]
