# Generated by Django 5.0.2 on 2024-04-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('ADVISOR', 'Advisor')], default='STUDENT', max_length=7),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
