# Generated by Django 5.0.2 on 2024-03-19 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_rename_mum_credits_course_num_credits_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Advisor',
        ),
        migrations.AddField(
            model_name='student',
            name='advisor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='planner.advisor'),
        ),
    ]
