# Generated by Django 5.0.2 on 2024-03-19 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_admin_class_year_alter_admin_eagle_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4)),
                ('mum_credits', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Program',
            new_name='Major',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='associated_programs',
            new_name='associated_majors',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='major_one',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='major_one', to='planner.major'),
        ),
        migrations.AddField(
            model_name='student',
            name='major_two',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='major_two', to='planner.major'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='course',
            name='associated_minors',
            field=models.ManyToManyField(to='planner.minor'),
        ),
        migrations.AddField(
            model_name='student',
            name='minor_one',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='minor_one', to='planner.minor'),
        ),
        migrations.AddField(
            model_name='student',
            name='minor_two',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='minor_two', to='planner.minor'),
        ),
    ]
