# Generated by Django 5.0.2 on 2024-03-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_advisoruser_studentuser_advisor_user_student_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvisorUser',
        ),
        migrations.DeleteModel(
            name='StudentUser',
        ),
        migrations.AlterField(
            model_name='student',
            name='end_semester',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Fall', 'Fall')], default='Spring', max_length=6),
        ),
    ]
