# Generated by Django 5.0.2 on 2024-04-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_planner_student_semester_planner_sem_eight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='class_description',
            new_name='course_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='class_code',
        ),
        migrations.RemoveField(
            model_name='course',
            name='class_days',
        ),
        migrations.RemoveField(
            model_name='course',
            name='class_location',
        ),
        migrations.RemoveField(
            model_name='course',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='class_professor',
        ),
        migrations.RemoveField(
            model_name='course',
            name='class_semester',
        ),
        migrations.RemoveField(
            model_name='course',
            name='class_time',
        ),
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(db_column='courseCode', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_corequisites',
            field=models.ManyToManyField(blank=True, related_name='required_with', to='planner.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_level',
            field=models.CharField(default='Undergraduate', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='course_prerequisites',
            field=models.ManyToManyField(blank=True, related_name='required_by', to='planner.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_semester',
            field=models.CharField(default='Every semester', max_length=15),
        ),
        migrations.AddField(
            model_name='course',
            name='course_title',
            field=models.CharField(db_column='title', default='', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='subject_area',
            field=models.CharField(db_column='subjectApiId', max_length=4, null=True),
        ),
    ]
