# Generated by Django 5.0.2 on 2024-03-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_delete_advisoruser_delete_studentuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='class_days',
            field=models.CharField(default='MWF', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='class_description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='class_location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='class_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='class_professor',
            field=models.CharField(default='Joe Smith', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='class_semester',
            field=models.CharField(default='Spring', max_length=6),
        ),
        migrations.AddField(
            model_name='course',
            name='class_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
