# Generated by Django 5.0.2 on 2024-03-20 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_course_class_days_course_class_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='advisor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.advisor'),
        ),
        migrations.AlterField(
            model_name='student',
            name='major_two',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='major_two', to='planner.major'),
        ),
        migrations.AlterField(
            model_name='student',
            name='minor_one',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minor_one', to='planner.minor'),
        ),
        migrations.AlterField(
            model_name='student',
            name='minor_two',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minor_two', to='planner.minor'),
        ),
    ]
